[package]
name = "scope"
version = "0.1.0"
authors = ["rademonster <sorenrade@gmail.com>"]

[dependencies]
glium = "0.20"
glium_text_rusttype = "0.3.1"

regex = "0.2.6"
clap = {version = "~2.30.0", features = ["yaml"]}

crossbeam-channel = "0.1"

color_set = { path = "color_set" }